// Code generated by the Encore 1.50.4 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly admin: admin.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly bot: bot.ServiceClient
    public readonly coin: coin.ServiceClient
    public readonly payment: payment.ServiceClient
    public readonly user: user.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.admin = new admin.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.bot = new bot.ServiceClient(base)
        this.coin = new coin.ServiceClient(base)
        this.payment = new payment.ServiceClient(base)
        this.user = new user.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getStatistics as api_admin_get_statistics_getStatistics } from "~backend/admin/get_statistics";
import { listAllBots as api_admin_list_all_bots_listAllBots } from "~backend/admin/list_all_bots";
import { listAllTopUps as api_admin_list_all_topups_listAllTopUps } from "~backend/admin/list_all_topups";
import { listUsers as api_admin_list_users_listUsers } from "~backend/admin/list_users";
import { manageBot as api_admin_manage_bot_manageBot } from "~backend/admin/manage_bot";
import { manageUser as api_admin_manage_user_manageUser } from "~backend/admin/manage_user";

export namespace admin {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getStatistics = this.getStatistics.bind(this)
            this.listAllBots = this.listAllBots.bind(this)
            this.listAllTopUps = this.listAllTopUps.bind(this)
            this.listUsers = this.listUsers.bind(this)
            this.manageBot = this.manageBot.bind(this)
            this.manageUser = this.manageUser.bind(this)
            this.getAllPackages = this.getAllPackages.bind(this)
            this.createPackage = this.createPackage.bind(this)
            this.updatePackage = this.updatePackage.bind(this)
            this.deletePackage = this.deletePackage.bind(this)
            this.getConfig = this.getConfig.bind(this)
            this.updateConfig = this.updateConfig.bind(this)
        }

        /**
         * Retrieves platform statistics for the admin dashboard.
         */
        public async getStatistics(): Promise<ResponseType<typeof api_admin_get_statistics_getStatistics>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/statistics`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_get_statistics_getStatistics>
        }

        /**
         * Retrieves all bots for admin monitoring.
         */
        public async listAllBots(): Promise<ResponseType<typeof api_admin_list_all_bots_listAllBots>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/bots`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_list_all_bots_listAllBots>
        }

        /**
         * Retrieves all top-ups for admin monitoring.
         */
        public async listAllTopUps(): Promise<ResponseType<typeof api_admin_list_all_topups_listAllTopUps>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/topups`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_list_all_topups_listAllTopUps>
        }

        /**
         * Retrieves all users for admin management.
         */
        public async listUsers(): Promise<ResponseType<typeof api_admin_list_users_listUsers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/users`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_list_users_listUsers>
        }

        /**
         * Manages a bot (extend, deactivate) from admin panel.
         */
        public async manageBot(params: RequestType<typeof api_admin_manage_bot_manageBot>): Promise<ResponseType<typeof api_admin_manage_bot_manageBot>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/manage-bot`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_manage_bot_manageBot>
        }

        /**
         * Manages a user's account (edit coins, delete, etc).
         */
        public async manageUser(params: RequestType<typeof api_admin_manage_user_manageUser>): Promise<ResponseType<typeof api_admin_manage_user_manageUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/manage-user`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_manage_user_manageUser>
        }

        /**
         * Get all coin packages (admin)
         */
        public async getAllPackages(): Promise<{ packages: any[] }> {
            const resp = await this.baseClient.callTypedAPI(`/admin/coin-packages`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver)
        }

        /**
         * Create new coin package
         */
        public async createPackage(params: { coins: number; price: number }): Promise<any> {
            const resp = await this.baseClient.callTypedAPI(`/admin/coin-packages`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver)
        }

        /**
         * Update coin package
         */
        public async updatePackage(params: { id: string; coins: number; price: number; active: boolean }): Promise<{ success: boolean }> {
            const resp = await this.baseClient.callTypedAPI(`/admin/coin-packages/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver)
        }

        /**
         * Delete coin package
         */
        public async deletePackage(params: { id: string }): Promise<{ success: boolean }> {
            const resp = await this.baseClient.callTypedAPI(`/admin/coin-packages/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver)
        }

        /**
         * Get system configuration
         */
        public async getConfig(): Promise<{ jadibotUrl: string }> {
            const resp = await this.baseClient.callTypedAPI(`/admin/config`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver)
        }

        /**
         * Update system configuration
         */
        public async updateConfig(params: { jadibotUrl: string }): Promise<{ success: boolean; message: string }> {
            const resp = await this.baseClient.callTypedAPI(`/admin/config`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver)
        }

        /**
         * Get all blocked users and IPs
         */
        public async getBlocks(): Promise<{ success: boolean; blockedUsers: any[]; blockedIPs: any[]; totalBlocked: number }> {
            const resp = await this.baseClient.callTypedAPI(`/admin/blocks`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver)
        }

        /**
         * Unblock a user or IP
         */
        public async unblock(params: { type: 'user' | 'ip'; identifier: string }): Promise<{ success: boolean; message: string }> {
            const resp = await this.baseClient.callTypedAPI(`/admin/unblock`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver)
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { login as api_auth_login_login } from "~backend/auth/login";
import { register as api_auth_register_register } from "~backend/auth/register";
import { resetPassword as api_auth_reset_password_resetPassword } from "~backend/auth/reset_password";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.login = this.login.bind(this)
            this.register = this.register.bind(this)
            this.resetPassword = this.resetPassword.bind(this)
            this.requestOtp = this.requestOtp.bind(this)
            this.verifyOtp = this.verifyOtp.bind(this)
            this.checkOtpStatus = this.checkOtpStatus.bind(this)
            this.checkUsername = this.checkUsername.bind(this)
        }

        /**
         * Authenticates a user and returns their information.
         */
        public async login(params: RequestType<typeof api_auth_login_login>): Promise<ResponseType<typeof api_auth_login_login>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_login_login>
        }

        /**
         * Registers a new user account.
         */
        public async register(params: RequestType<typeof api_auth_register_register>): Promise<ResponseType<typeof api_auth_register_register>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/register`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_register_register>
        }

        /**
         * Resets the user's password.
         */
        public async resetPassword(params: RequestType<typeof api_auth_reset_password_resetPassword>): Promise<ResponseType<typeof api_auth_reset_password_resetPassword>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/reset-password`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_reset_password_resetPassword>
        }

        /**
         * Request OTP for email verification during registration
         */
        public async requestOtp(params: { email: string; name: string }): Promise<{ message: string }> {
            const resp = await this.baseClient.callTypedAPI(`/auth/request-otp`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver)
        }

        /**
         * Verify OTP code
         */
        public async verifyOtp(params: { email: string; otp: string }): Promise<{ success: boolean; message: string }> {
            const resp = await this.baseClient.callTypedAPI(`/auth/verify-otp`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver)
        }

        /**
         * Check OTP status and remaining time
         */
        public async checkOtpStatus(params: { email: string }): Promise<{ verified: boolean; remainingSeconds: number }> {
            const resp = await this.baseClient.callTypedAPI(`/auth/otp-status?email=${encodeURIComponent(params.email)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver)
        }

        /**
         * Check if username is available
         */
        public async checkUsername(params: { username: string }): Promise<{ available: boolean; message: string }> {
            const resp = await this.baseClient.callTypedAPI(`/auth/check-username?username=${encodeURIComponent(params.username)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver)
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { deactivateBot as api_bot_deactivate_bot_deactivateBot } from "~backend/bot/deactivate_bot";
import { extendBot as api_bot_extend_bot_extendBot } from "~backend/bot/extend_bot";
import { listBots as api_bot_list_bots_listBots } from "~backend/bot/list_bots";
import { purchase as api_bot_purchase_purchase } from "~backend/bot/purchase";

export namespace bot {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deactivateBot = this.deactivateBot.bind(this)
            this.extendBot = this.extendBot.bind(this)
            this.listBots = this.listBots.bind(this)
            this.purchase = this.purchase.bind(this)
            this.cleanupOrphanedBots = this.cleanupOrphanedBots.bind(this)
            this.triggerAutoCleanup = this.triggerAutoCleanup.bind(this)
        }

        /**
         * Deactivates a bot subscription.
         */
        public async deactivateBot(params: RequestType<typeof api_bot_deactivate_bot_deactivateBot>): Promise<ResponseType<typeof api_bot_deactivate_bot_deactivateBot>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bot/deactivate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_bot_deactivate_bot_deactivateBot>
        }

        /**
         * Extends the expiration date of a bot subscription.
         */
        public async extendBot(params: RequestType<typeof api_bot_extend_bot_extendBot>): Promise<ResponseType<typeof api_bot_extend_bot_extendBot>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bot/extend`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_bot_extend_bot_extendBot>
        }

        /**
         * Retrieves all bots owned by the user.
         */
        public async listBots(params: { userId: string }): Promise<ResponseType<typeof api_bot_list_bots_listBots>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bot/list/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_bot_list_bots_listBots>
        }

        /**
         * Purchases a new bot subscription for the user.
         */
        public async purchase(params: RequestType<typeof api_bot_purchase_purchase>): Promise<ResponseType<typeof api_bot_purchase_purchase>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bot/purchase`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_bot_purchase_purchase>
        }

        /**
         * Cleanup orphaned bots (bots without sessions on SC BOT server)
         */
        public async cleanupOrphanedBots(params: { username?: string }): Promise<any> {
            const resp = await this.baseClient.callTypedAPI(`/bot/cleanup-orphaned`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver)
        }

        /**
         * Trigger auto cleanup for all orphaned bots
         */
        public async triggerAutoCleanup(): Promise<any> {
            const resp = await this.baseClient.callTypedAPI(`/bot/trigger-cleanup-orphaned`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver)
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getDeductions as api_coin_get_deductions_getDeductions } from "~backend/coin/get_deductions";

export namespace coin {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getBalance = this.getBalance.bind(this)
            this.getDeductions = this.getDeductions.bind(this)
            this.getHistory = this.getHistory.bind(this)
            this.topUp = this.topUp.bind(this)
            this.getPackages = this.getPackages.bind(this)
        }

        /**
         * Retrieves the user's current coin balance.
         */
        public async getBalance(params: { userId: string }): Promise<ResponseType<typeof api_coin_get_balance_getBalance>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/coin/balance/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_coin_get_balance_getBalance>
        }

        /**
         * Retrieves the user's coin deduction history.
         */
        public async getDeductions(params: { userId: number }): Promise<ResponseType<typeof api_coin_get_deductions_getDeductions>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/coin/deductions/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_coin_get_deductions_getDeductions>
        }

        /**
         * Retrieves the user's top-up history.
         */
        public async getHistory(params: { userId: string }): Promise<ResponseType<typeof api_coin_get_history_getHistory>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/coin/history/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_coin_get_history_getHistory>
        }

        /**
         * Creates a new top-up request for the user.
         */
        public async topUp(params: RequestType<typeof api_coin_top_up_topUp>): Promise<ResponseType<typeof api_coin_top_up_topUp>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/coin/top-up`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_coin_top_up_topUp>
        }

        /**
         * Get active coin packages for users
         */
        public async getPackages(): Promise<{ packages: any[] }> {
            const resp = await this.baseClient.callTypedAPI(`/coin/packages`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver)
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getChannels as api_payment_get_channels_getChannels } from "~backend/payment/get_channels";
import { createPayment as api_payment_create_transaction_createPayment } from "~backend/payment/create_transaction";
import { getTransaction as api_payment_get_transaction_getTransaction } from "~backend/payment/get_transaction";
import { getUserTransactions as api_payment_get_transaction_getUserTransactions } from "~backend/payment/get_transaction";
import { checkStatus as api_payment_get_transaction_checkStatus } from "~backend/payment/get_transaction";
import { handleCallback as api_payment_callback_handleCallback } from "~backend/payment/callback";

export namespace payment {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getChannels = this.getChannels.bind(this)
            this.createPayment = this.createPayment.bind(this)
            this.getTransaction = this.getTransaction.bind(this)
            this.getUserTransactions = this.getUserTransactions.bind(this)
            this.checkStatus = this.checkStatus.bind(this)
            this.handleCallback = this.handleCallback.bind(this)
            this.calculateFee = this.calculateFee.bind(this)
        }

        /**
         * Get available payment channels from Tripay
         */
        public async getChannels(): Promise<ResponseType<typeof api_payment_get_channels_getChannels>> {
            const resp = await this.baseClient.callTypedAPI(`/payment/channels`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payment_get_channels_getChannels>
        }

        /**
         * Create a new payment transaction
         */
        public async createPayment(params: RequestType<typeof api_payment_create_transaction_createPayment>): Promise<ResponseType<typeof api_payment_create_transaction_createPayment>> {
            const resp = await this.baseClient.callTypedAPI(`/payment/create`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payment_create_transaction_createPayment>
        }

        /**
         * Get transaction detail by reference
         */
        public async getTransaction(params: { reference: string }): Promise<ResponseType<typeof api_payment_get_transaction_getTransaction>> {
            const resp = await this.baseClient.callTypedAPI(`/payment/transaction/${encodeURIComponent(params.reference)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payment_get_transaction_getTransaction>
        }

        /**
         * Get all transactions for a user
         */
        public async getUserTransactions(params: { userId: string }): Promise<ResponseType<typeof api_payment_get_transaction_getUserTransactions>> {
            const resp = await this.baseClient.callTypedAPI(`/payment/transactions/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payment_get_transaction_getUserTransactions>
        }

        /**
         * Check transaction status
         */
        public async checkStatus(params: { reference: string }): Promise<ResponseType<typeof api_payment_get_transaction_checkStatus>> {
            const resp = await this.baseClient.callTypedAPI(`/payment/check-status/${encodeURIComponent(params.reference)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payment_get_transaction_checkStatus>
        }

        /**
         * Handle payment callback from Tripay
         */
        public async handleCallback(params: RequestType<typeof api_payment_callback_handleCallback>): Promise<ResponseType<typeof api_payment_callback_handleCallback>> {
            const resp = await this.baseClient.callTypedAPI(`/payment/callback`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payment_callback_handleCallback>
        }

        /**
         * Calculate payment fee from Tripay
         */
        public async calculateFee(params: { code: string; amount: number }): Promise<any> {
            const resp = await this.baseClient.callTypedAPI(`/payment/calculate-fee/${encodeURIComponent(params.code)}/${encodeURIComponent(params.amount)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver)
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getProfile as api_user_get_profile_getProfile } from "~backend/user/get_profile";
import { updateProfile as api_user_update_profile_updateProfile } from "~backend/user/update_profile";

export namespace user {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getProfile = this.getProfile.bind(this)
            this.updateProfile = this.updateProfile.bind(this)
        }

        /**
         * Retrieves the user's profile information.
         */
        public async getProfile(params: { userId: string }): Promise<ResponseType<typeof api_user_get_profile_getProfile>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_get_profile_getProfile>
        }

        /**
         * Updates the user's profile information.
         */
        public async updateProfile(params: RequestType<typeof api_user_update_profile_updateProfile>): Promise<ResponseType<typeof api_user_update_profile_updateProfile>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                avatar:   params.avatar,
                email:    params.email,
                name:     params.name,
                password: params.password,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user/${encodeURIComponent(params.userId)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_update_profile_updateProfile>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    // Skip strings that are already formatted with timezone (e.g., "wib")
    if (value.toLowerCase().includes('wib')) {
      return value;
    }
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.50.4)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

// Membuat client dengan konfigurasi default
const client = new Client(import.meta.env.VITE_CLIENT_TARGET, { 
    requestInit: { 
        credentials: "include" 
    }
});

// Menambahkan interceptor untuk request
client.interceptRequest = (request) => {
    // Mendapatkan token dari localStorage
    if (typeof window !== 'undefined' && window.localStorage) {
        const token = window.localStorage.getItem('token');
        if (token) {
            // Menambahkan header Authorization
            request.headers = request.headers || {};
            request.headers['Authorization'] = `Bearer ${token}`;
        }
    }
    return request;
};

export default client;
